# Collate translation files into a single translations file

In [46]:
import pandas as pd

sources = pd.read_csv("data/sources.tsv", index_col="id", sep="\t")
sources.head()

    template_type occupation source_gender                          source
id
1               1  bartender       neutral  I used to work as a bartender.
2               2  bartender       neutral          I am a poor bartender.
3               3  bartender       neutral          I am a nice bartender.
4               4  bartender       neutral  The bartender called me today.
5               5  bartender        female            Anne is a bartender.

In [47]:
translations = pd.DataFrame(
    columns=['template_type', 'occupation', 'source_gender', 'source', 'model', 'pipeline', 'target', 'target_gender'])

Zero-shot translations

In [48]:
mbart_zeroshot = pd.read_csv("../data/mbart.zeroshot.translations.tsv", index_col="id", sep="\t")
mbart_zeroshot['model'] = 'mbart'
mbart_zeroshot['pipeline'] = 'zeroshot'
mbart_zeroshot['target'] = mbart_zeroshot['mbart_hypothesis']
mbart_zeroshot['target_gender'] = None
mbart_zeroshot.drop(columns=['mbart_hypothesis'], inplace=True)
translations = pd.concat([translations, mbart_zeroshot], ignore_index=True)
translations.head()

,template_type,occupation,source_gender,source,model,pipeline,target,target_gender
0,1,bartender,neutral,I used to work as a bartender.,mbart,zeroshot,Я працював барменом.,None
1,2,bartender,neutral,I am a poor bartender.,mbart,zeroshot,Я бідний бармен.,None
2,3,bartender,neutral,I am a nice bartender.,mbart,zeroshot,Я хороший бармен.,None
3,4,bartender,neutral,The bartender called me today.,mbart,zeroshot,Бармен зателефонував мені сьогодні.,None
4,5,bartender,female,Anne is a bartender.,mbart,zeroshot,Анна - бармен.,None

In [49]:
opusmt_zeroshot = pd.read_csv("../data/opusmt.zeroshot.translations.tsv", index_col="id", sep="\t")
opusmt_zeroshot['model'] = 'opusmt'
opusmt_zeroshot['pipeline'] = 'zeroshot'
opusmt_zeroshot['target'] = opusmt_zeroshot['opusmt_hypothesis']
opusmt_zeroshot['target_gender'] = None
opusmt_zeroshot.drop(columns=['opusmt_hypothesis'], inplace=True)
translations = pd.concat([translations, opusmt_zeroshot], ignore_index=True)
translations.head()

,template_type,occupation,source_gender,source,model,pipeline,target,target_gender
0,1,bartender,neutral,I used to work as a bartender.,mbart,zeroshot,Я працював барменом.,None
1,2,bartender,neutral,I am a poor bartender.,mbart,zeroshot,Я бідний бармен.,None
2,3,bartender,neutral,I am a nice bartender.,mbart,zeroshot,Я хороший бармен.,None
3,4,bartender,neutral,The bartender called me today.,mbart,zeroshot,Бармен зателефонував мені сьогодні.,None
4,5,bartender,female,Anne is a bartender.,mbart,zeroshot,Анна - бармен.,None

Gender tags

In [54]:
mbart_tagged = pd.read_csv('../data/mbart.tagged.translations.tsv', index_col=None, sep="\t")
tagged = mbart_zeroshot.copy()
tagged['target'] = mbart_tagged['mbart_hypothesis'].values
tagged['pipeline'] = 'tagged'
translations = pd.concat([translations, tagged], ignore_index=True)
translations.head(10)

,template_type,occupation,source_gender,source,model,pipeline,target,target_gender
0,1,bartender,neutral,I used to work as a bartender.,mbart,zeroshot,Я працював барменом.,None
1,2,bartender,neutral,I am a poor bartender.,mbart,zeroshot,Я бідний бармен.,None
2,3,bartender,neutral,I am a nice bartender.,mbart,zeroshot,Я хороший бармен.,None
3,4,bartender,neutral,The bartender called me today.,mbart,zeroshot,Бармен зателефонував мені сьогодні.,None
4,5,bartender,female,Anne is a bartender.,mbart,zeroshot,Анна - бармен.,None
5,6,bartender,female,Anne is an experienced bartender.,mbart,zeroshot,Анна - досвідчений бармен.,None
6,7,bartender,male,Tom is a bartender.,mbart,zeroshot,Том - бармен.,None
7,8,bartender,male,Tom is a poor bartender.,mbart,zeroshot,Том - бідний бармен.,None
8,9,bartender,neutral,Jessie is a good bartender.,mbart,zeroshot,Джесси - хороший бармен.,None
9,10,bartender,neutral,Jessie is a poor bartender.,mbart,zeroshot,Джесси - бідний бармен.,None

In [55]:
opusmt_tagged = pd.read_csv('../data/opusmt.tagged.translations.tsv', index_col=None, sep="\t")
tagged = opusmt_zeroshot.copy()
tagged['target'] = opusmt_tagged['opusmt_hypothesis'].values
tagged['pipeline'] = 'tagged'
translations = pd.concat([translations, tagged], ignore_index=True)
translations.head(10)

,template_type,occupation,source_gender,source,model,pipeline,target,target_gender
0,1,bartender,neutral,I used to work as a bartender.,mbart,zeroshot,Я працював барменом.,None
1,2,bartender,neutral,I am a poor bartender.,mbart,zeroshot,Я бідний бармен.,None
2,3,bartender,neutral,I am a nice bartender.,mbart,zeroshot,Я хороший бармен.,None
3,4,bartender,neutral,The bartender called me today.,mbart,zeroshot,Бармен зателефонував мені сьогодні.,None
4,5,bartender,female,Anne is a bartender.,mbart,zeroshot,Анна - бармен.,None
5,6,bartender,female,Anne is an experienced bartender.,mbart,zeroshot,Анна - досвідчений бармен.,None
6,7,bartender,male,Tom is a bartender.,mbart,zeroshot,Том - бармен.,None
7,8,bartender,male,Tom is a poor bartender.,mbart,zeroshot,Том - бідний бармен.,None
8,9,bartender,neutral,Jessie is a good bartender.,mbart,zeroshot,Джесси - хороший бармен.,None
9,10,bartender,neutral,Jessie is a poor bartender.,mbart,zeroshot,Джесси - бідний бармен.,None

LLM corrected

In [56]:
mbart_llm = pd.read_csv("../data/mbart.llm_corrected.translations.tsv", sep="\t")
mbart_llm['model'] = 'mbart'
mbart_llm['pipeline'] = 'llm'
mbart_llm['target'] = mbart_llm['mbart_llm_corrected']
mbart_llm['target_gender'] = None
mbart_llm.drop(columns=['mbart_hypothesis', 'mbart_llm_corrected'], inplace=True)
translations = pd.concat([translations, mbart_llm], ignore_index=True)
translations.head()

,template_type,occupation,source_gender,source,model,pipeline,target,target_gender
0,1,bartender,neutral,I used to work as a bartender.,mbart,zeroshot,Я працював барменом.,None
1,2,bartender,neutral,I am a poor bartender.,mbart,zeroshot,Я бідний бармен.,None
2,3,bartender,neutral,I am a nice bartender.,mbart,zeroshot,Я хороший бармен.,None
3,4,bartender,neutral,The bartender called me today.,mbart,zeroshot,Бармен зателефонував мені сьогодні.,None
4,5,bartender,female,Anne is a bartender.,mbart,zeroshot,Анна - бармен.,None

In [57]:
opusmt_llm = pd.read_csv("../data/opusmt.llm_corrected.translations.tsv", sep="\t")
opusmt_llm['model'] = 'opusmt'
opusmt_llm['pipeline'] = 'llm'
opusmt_llm['target'] = opusmt_llm['opusmt_llm_corrected']
opusmt_llm['target_gender'] = None
opusmt_llm.drop(columns=['opusmt_hypothesis', 'opusmt_llm_corrected'], inplace=True)
translations = pd.concat([translations, opusmt_llm], ignore_index=True)
translations.head()

,template_type,occupation,source_gender,source,model,pipeline,target,target_gender
0,1,bartender,neutral,I used to work as a bartender.,mbart,zeroshot,Я працював барменом.,None
1,2,bartender,neutral,I am a poor bartender.,mbart,zeroshot,Я бідний бармен.,None
2,3,bartender,neutral,I am a nice bartender.,mbart,zeroshot,Я хороший бармен.,None
3,4,bartender,neutral,The bartender called me today.,mbart,zeroshot,Бармен зателефонував мені сьогодні.,None
4,5,bartender,female,Anne is a bartender.,mbart,zeroshot,Анна - бармен.,None

In [58]:
translations.to_csv('translations.tsv', sep='\t', index=False)